Updates

diff --git a/bin/,editexecutable b/bin/,editexecutable
--- a/bin/,editexecutable
+++ b/bin/,editexecutable
@@ -5,8 +5,11 @@ if (($# == 1)) && [[ "$1" == "--bash-completion" ]]; then
 	return
 fi
 
+log() {
+	echo "$name:" "$*" >&2
+}
 fatal() {
-	echo "$name: ERROR:" "$*" >&2
+	log "ERROR: $*"
 	exit 1
 }
 
@@ -16,9 +19,18 @@ usage() {
 Usage: $name executablefile
 
 Edit executable file.
+
+    -c  Create executable in \$KCDIR/bin
+
+Written by Kamil Cukrowski 2021
 EOF
 }
 
+create=0
+if (($#)) && [[ "$1" == '-c' ]]; then
+	create=1
+	shift
+fi
 if (($# == 0)); then
 	usage
 	exit 1
@@ -27,7 +39,18 @@ if (($# != 1)); then
 	fatal "Too many arguments"
 fi
 if ! l=$(command -v "$1") || ! [[ -x "$l" ]]; then
-	fatal "No executable found: $1"
+	if ((!create)); then
+		fatal "No executable found: $1"
+	fi
+	if [[ ! -e "${KCDIR:-}" ]]; then
+		KCDIR=~/.kamilscripts
+	fi
+	if [[ ! -e ~/.kamilscripts ]]; then
+		fatal "KCDIR not found"
+	fi
+	l="$KCDIR/bin/$1"
+	log "Creating executable at: $l"
+	sleep 1
 fi
 
 set -x
