Update editexecutable with command -v

diff --git a/bin/,editexecutable b/bin/,editexecutable
--- a/bin/,editexecutable
+++ b/bin/,editexecutable
@@ -5,6 +5,11 @@ if (($# == 1)) && [[ "$1" == "--bash-completion" ]]; then
 	return
 fi
 
+fatal() {
+	echo "$name: ERROR:" "$*" >&2
+	exit 1
+}
+
 name=$(basename -- "$0")
 usage() {
 		cat <<EOF
@@ -18,19 +23,12 @@ if (($# == 0)); then
 	usage
 	exit 1
 fi
-if ! l=$(which "$1"); then
-	echo "$name: ERROR: No executable found $l";
-	exit 1
+if (($# != 1)); then
+	fatal "Too many arguments"
 fi
-for i in $(cut -d: -f2- <<<"$l"); do
-	if [[ ! -x "$i" ]]; then
-		l=$i;
-		break
-	fi
-done
-if [[ -z "$l" ]]; then
-	echo "$name: ERROR: No executable found 2";
-	exit 1
+if ! l=$(command -v "$1") || ! [[ -x "$l" ]]; then
+	fatal "No executable found: $1"
 fi
+
 set -x
 ${EDITOR:-vim} "$l"
