weelxavt067d.striketechnologies.com: Updates

diff --git a/bin/,tidyimportsisortblack b/bin/,tidyimportsisortblack
--- a/bin/,tidyimportsisortblack
+++ b/bin/,tidyimportsisortblack
@@ -1,18 +1,37 @@
 #!/bin/bash
 set -euo pipefail
-if [[ $# == 1 && ( "$1" == -h || "$1" == --help ) || $# -gt 1 ]]; then
+
+hascmd() {
+	hash "$@" 2>/dev/null
+}
+
+if [[ $# == 1 && ("$1" == -h || "$1" == --help) || $# -gt 1 ]]; then
 	echo "Usage: $1 file"
 	exit 1
 fi
-if (($# == 1)); then
-	exec 1<"$1"
+
+pkg=()
+if ! hascmd tidy-imports; then pkg+=(pyflyby); fi
+if ! hascmd isort; then pkg+=(isort); fi
+if ! hascmd black; then pkg+=(black); fi
+if "${#pkg[@]}"; then
+	echo "ERROR: execute pip install --user ${pkg[*]}" >&2
+	exit 2
 fi
+
+if (($# == 1)); then
+	exec 0<"$1"
+fi
+
 if tmp=$(
 	tidy-imports --black --quiet --replace-star-imports |
-	isort --stdout --quiet --profile black - |
-	black --quiet -
+		isort --stdout --quiet --profile black - |
+		black --quiet -
 ); then
 	echo "$tmp"
 else
+	if [[ -n "$tmp" ]]; then
+		echo "$tmp" >&2
+	fi
 	exit "$?"
 fi
