up

diff --git a/bin/l b/bin/l
--- a/bin/l
+++ b/bin/l
@@ -1,29 +1,18 @@
 #!/bin/bash
+set -euo pipefail
 # Written by Kamil Cukrowski 14.cze.2021
 # SPDX-License-Identifier: MIT + Beerware
 # Licensed jointly under MIT License and Beerware License
 
 fallback=0
-if (($# >= 1)) && [[ "${1:0:1}" == "-" ]]; then
+if
 	# If any options are passed, fallback to ls.
-	fallback=1
-elif tmp=$(cut --help 2>&1) && [[ "$tmp" == *"-z"* ]]; then
-	# We need cut -z to operate.
-	cut_z_chars() {
-		cut -z -c"$1" "$2"
-	}
-	cut_z_chars_since() {
-		cut -z -c"$1"- "$2"
-	}
-elif tmp=$(awk --version 2>&1) && [[ "$tmp" == *"GNU"* ]]; then
-	# Use GNU awk if available.
-	cut_z_chars() {
-		awk -v N="$1" 'BEGIN{ RS="\0"; ORS="\0"; } {print substr($0,N,1)}' "$2"
-	}
-	cut_z_chars_since() {
-		awk -v N="$1" 'BEGIN{ RS="\0"; ORS="\0"; } {print substr($0,N)}' "$2"
-	}
-else
+	{ (($# >= 1)) && [[ "${1:0:1}" == "-" ]] ;} ||
+	# If awk is not GNU
+	! hash awk 2>/dev/null >/dev/null ||
+	! tmp=$(awk --version 2>&1) ||
+	[[ "$tmp" != *"GNU"* ]]
+then
 	fallback=1
 fi
 
@@ -47,7 +36,7 @@ fatal() {
 }
 
 _ls=(
-	ls -aldFhU --color=auto
+	ls -aldFhU --color=auto --group-directories-first
 )
 
 findargs=(
@@ -74,66 +63,101 @@ findargs=(
 
 dodirlist() {
 	if ! cd "$1"; then
-		fatal "Could not change directory: $1"
+		fatal "could not open directory: $1"
 	fi
-	LC_ALL=C find . "${findargs[@]}" | LC_ALL=C sort -z > "$tmpf" ||:
-	# Print "total ..." summary line:
-	cut_z_chars 1 "$tmpf" | LC_ALL=C tr '\0' '\n' | LC_ALL=C awk '
-		#BEGIN{
-		#	lower["a"]; lower["b"]; lower["c"]; lower["d"]; lower["e"]; lower["f"]; lower["g"];
-		#	upper["A"]; upper["B"]; upper["C"]; upper["D"]; upper["E"]; upper["F"]; upper["G"];
-		#}
-		#$1 in upper { hidden += $1 }
-		$1 == "a" || $1 == "A" { dirs++;   next }
-		$1 == "g" || $1 == "G" { files++;  next }
-		#$1 == "b" || $1 == "B" { links++   }
-		#$1 == "c" || $1 == "C" { pipes++   }
-		#$1 == "d" || $1 == "D" { sockets++ }
-		#$1 == "e" || $1 == "E" { blocks++  }
-		#$1 == "f" || $1 == "F" { chars++   }
+	if ! find . "${findargs[@]}" | awk '
+		BEGIN {
+			RS = "\0"
+			ORS = "\0"
+			#	lower["a"]; lower["b"]; lower["c"]; lower["d"]; lower["e"]; lower["f"]; lower["g"];
+			#	upper["A"]; upper["B"]; upper["C"]; upper["D"]; upper["E"]; upper["F"]; upper["G"];
+		}
+
+		{
+			lines[NR] = $0
+			type = substr($0, 1, 1)
+		}
+
+		# type in upper { hidden += type }
+		type == "a" || type == "A" { dirs++;   next }
+		type == "g" || type == "G" { files++;  next }
+		# type == "b" || type == "B" { links++   }
+		# type == "c" || type == "C" { pipes++   }
+		# type == "d" || type == "D" { sockets++ }
+		# type == "e" || type == "E" { blocks++  }
+		# type == "f" || type == "F" { chars++   }
 		{ other++ }
-		END{
-			printf("total %d directories, %d files, %d other\n", dirs, files, other)
-		}'
-	# Actually call ls to do the printing.
-	if ! {
-			printf "%s\0" . ..
-			cut_z_chars_since 2 "$tmpf"
-		} | xargs -0 -r "${_ls[@]}"
+
+		END {
+			fmt = "total %d directories, %d files, %d other\n"
+			if (ENVIRON["LANGUAGE"] == "pl") {
+				fmt = "razem %d katalogów, %d plików, %d innych\n"
+			}
+
+			# Print "total ..." summary line:
+			printf(fmt, dirs, files, other) > "/dev/fd/3"
+
+			# Output lines for ls
+			print(".")
+			print("..")
+			n = asort(lines)
+			for (i = 1; i <= n; ++i) {
+				print(substr(lines[i], 2))
+			}
+		}
+		' | xargs -0 -r "${_ls[@]}"
 	then
 		fatal "ls failed"
 	fi
 	if ! cd - >/dev/null; then
-		fatal "Could not change directory back from: $1"
+		fatal "could not change directory back from: $1"
 	fi
 }
 
-dols() {
-	if [[ -d "$1" ]]; then
-		printf "%q:\n" "$1"
-		dodirlist "$1"
-	else
-		if ! "${_ls[@]}" "$1"; then
-			fatal "ls failed"
-		fi
+call_ls() {
+	if ! "${_ls[@]}" "$@"; then
+		fatal "ls failed"
 	fi
 }
 
-tmpf=$(mktemp)
-trap_exit() {
-	rm "$tmpf"
-}
-trap trap_exit EXIT
+# Main ##############################################################################
+
+# Preserve stdout for awk script.
+exec 3>&1
 
 if (($# == 0)); then
-	dodirlist .
-else
-	dols "$1"
-	shift
-	for i in "$@"; do
-		echo
-		dols "$i"
-	done
+	set -- .
+fi
+if (($# == 1)); then
+	if [[ -d "$1" ]]; then
+		dodirlist "$1"
+	else
+		call_ls "$1"
+	fi
+	exit
 fi
 
+files=()
+dirs=()
+while (($#)); do
+	if [[ -d "$1" ]]; then
+		dirs+=("$1")
+	else
+		files+=("$1")
+	fi
+	shift
+done
+prev=0
+if ((${#files[@]})); then
+	call_ls "${files[@]}"
+	prev=1
+fi
+if ((${#dirs[@]})); then
+	readarray -d '' -t dirs < <(printf '%s\0' "${dirs[@]}" | sort -z)
+	for i in "${dirs[@]}"; do
+		if ((prev++)); then echo; fi
+		printf "%q:\n" "$i"
+		dodirlist "$i"
+	done
+fi
 
